# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 695)
        self.name_label = QtWidgets.QLabel(Form)
        self.name_label.setGeometry(QtCore.QRect(10, 20, 51, 31))
        self.name_label.setObjectName("name_label")
        self.name_edit = QtWidgets.QLineEdit(Form)
        self.name_edit.setGeometry(QtCore.QRect(70, 20, 201, 31))
        self.name_edit.setObjectName("name_edit")
        self.number_label = QtWidgets.QLabel(Form)
        self.number_label.setGeometry(QtCore.QRect(10, 71, 51, 31))
        self.number_label.setObjectName("number_label")
        self.number_edit = QtWidgets.QLineEdit(Form)
        self.number_edit.setGeometry(QtCore.QRect(70, 70, 201, 31))
        self.number_edit.setObjectName("number_edit")
        self.upload_button = QtWidgets.QPushButton(Form)
        self.upload_button.setGeometry(QtCore.QRect(280, 120, 101, 31))
        self.upload_button.setObjectName("upload_button")
        self.save_button = QtWidgets.QPushButton(Form)
        self.save_button.setGeometry(QtCore.QRect(280, 70, 101, 31))
        self.save_button.setObjectName("save_button")
        self.number_button = QtWidgets.QPushButton(Form)
        self.number_button.setGeometry(QtCore.QRect(280, 20, 101, 31))
        self.number_button.setObjectName("number_button")
        self.listView = QtWidgets.QListView(Form)
        self.listView.setGeometry(QtCore.QRect(10, 331, 351, 321))
        self.listView.setObjectName("listView")
        self.photo_label = QtWidgets.QLabel(Form)
        self.photo_label.setGeometry(QtCore.QRect(10, 110, 201, 211))
        self.photo_label.setText("")
        self.photo_label.setPixmap(QtGui.QPixmap("이정재.png"))
        self.photo_label.setScaledContents(True)
        self.photo_label.setObjectName("photo_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name_label.setText(_translate("Form", "이 름"))
        self.number_label.setText(_translate("Form", "전화번호"))
        self.upload_button.setText(_translate("Form", "사진등록"))
        self.save_button.setText(_translate("Form", "주소록저장"))
        self.number_button.setText(_translate("Form", "주소록불러오기"))
